### ISSUE TITLE
Storm should detect correct nimbus.host on mutli-master mesos cluster

### ISSUE THREAD

**Issue by ondrej-smola** [mesos/storm#25]
My setup:
3 masters (mesos, marathon, chronos, storm) - ubuntu trusty
ips: 192.168.56.{10,11,12} - MASTER(1,2,3)

Using latest build (storm-mesos 0.9.3) + mesos 0.21.1
Running storm UI on all masters
Nimbus get started from Master1

After startup mesos elects MASTER2 to be leader.

storm.yaml

```yaml

mesos.master.url: "zk://192.168.56.10:2181,192.168.56.11:2181,192.168.56.12:2181/mesos"

storm.zookeeper.servers:
  - 192.168.56.10
  - 192.168.56.11
  - 192.168.56.12

nimbus.host: 192.168.56.11  
mesos.executor.uri: "//opt/storm-mesos-0.9.3.tgz"

storm.messaging.transport: "backtype.storm.messaging.netty.Context"

storm.local.dir: "/opt/storm_local"
storm.log.dir: "/var/log/storm"

ui.port: 9998

mesos.framework.role: "*"
mesos.framework.checkpoint: false
mesos.framework.name: "Storm 0.9.3"

```

When i correcly specify MASTER2(current leader) as nimbus.host - UI works, but when i use MASTER1 or MASTER3 ip i get connection refused. My problem is that setup is automated (Ansible) and dont know which master get elected.
